"""empty message

Revision ID: 4ff1308920a7
Revises: c4506bdb30e8
Create Date: 2020-11-27 12:16:26.651210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff1308920a7'
down_revision = 'c4506bdb30e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'p_photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('p_photo', sa.VARCHAR(), server_default=sa.text("'/static/img/50.jpg'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
