"""empty message

Revision ID: c4506bdb30e8
Revises: 
Create Date: 2020-11-27 12:03:20.538399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4506bdb30e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('p_photo', sa.String(), server_default='/static/img/50.jpg', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'p_photo')
    # ### end Alembic commands ###
